=== tuongvythaivo493-ui/xml_thaivotuongvy/buoi3/2.2/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="school">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="date" type="xs:date" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required" />
                        <xs:attribute name="email" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

        <!-- Ràng buộc email phải duy nhất trong school -->
        <xs:unique name="UniqueStudentEmail">
            <xs:selector xpath="student" />
            <xs:field xpath="@email" />
        </xs:unique>

    </xs:element>

</xs:schema>

=== tuongvythaivo493-ui/xml_thaivotuongvy/buoi3/2.2/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<school xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="students.xsd">

    <student id="SV01" email="sv01@example.com">
        <name>Nguyễn Thị Thanh Thủy</name>
        <date>1997-12-20</date>
    </student>

    <student id="SV02" email="sv02@example.com">
        <name>Lê Thị Hồng Cẩm</name>
        <date>1998-01-21</date>
    </student>

    <student id="SV03" email="sv03@example.com">
        <name>Trần Văn An</name>
        <date>1997-11-11</date>
    </student>

</school>
